Sprint 4 forum
southpark-team/game pull request #29
Opened 2022-03-21 17:34 UTC by mikhailbys

Реализовано:
- Страница форума со списком топиков. (без пагинации, без кнопок действия над топиками, кроме создания)
- Страница топика.
-  Список комментариев топика, с возможностью отправить новый комментарий. (Внутри страницы топика).
- Страница создания/редактирования топика. (Не хватает только кнопки перехода в редактирование).

*На комментариях нет автора - нужно получать каждого через user_id, нужно сделать и замапить представление в бд, где будут подгружены имена авторов для комментариев.

2022-03-21 18:39 UTC, DmitryKhitrin requested changes
Вообще, выглядит хорошо, но с кридами и типами давайте попробуем разобраться.

2022-03-21 18:39 UTC, DmitryKhitrin commented on docker-compose.yaml
> +        PGADMIN_LISTEN_PORT: 7070
Это все нужно брать из файла с переменным окружением, не надо хранить пароли в образе

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/actions/comments.actions.ts
> +    payload: { data },
Почему просто не `payload: data`?

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/actions/comments.actions.ts
> +            // loadComment();
Это должно быть закомментированно?

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/actions/comments.actions.ts
> +): ThunkAction<void, unknown, unknown, AnyAction> => async (dispatch, _state) => {
```suggestion
): ThunkAction<void, unknown, unknown, AnyAction> => async (dispatch) => {
```

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/Forum/Forum.helpers.ts
> +} from "react";
```suggestion
import { useRef } from "react";
```

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/Forum/Forum.view.tsx
> +    const columns: ColumnsType<ForumRecord> = [
Это можно вынести куда-нибудь в константу, в таком виде на каждый рендер переменная перезаписывается и на нее меняется ссылка, ну в крайнем случае в useMemo

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/LeaderBoard/LeaderBoard.helpers.ts
> +    const [tableScroll, setTableScroll] = useState(window?.innerHeight);
Тут на всякий случай нужен typeof `window !== undefined`

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/LeaderBoard/LeaderBoard.helpers.ts
> +    const [tableScroll, setTableScroll] = useState(window?.innerHeight);
Такое обычно стреляет в неожиданном месте на этапе ssr

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/Topic/components/CommentInput/CommentInput.view.tsx
> +    const { isLoading } = useSelector((state) => state.comments, shallowEqual);
Зачем тут 3 селектора? Обычно все объединяют в один

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/Topic/components/CommentInput/CommentInput.view.tsx
> +    const handleInput = useCallback((e: any) => setMessage(e.target.value), []);
` React.ChangeEvent<HTMLInputElement>`

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/Topic/components/Comments/Comments.helpers.ts
> +    useMountEffect(() => {
Этот компонент разве не должен грузить новые коммента при смене id?

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/Topic/components/Comments/Comments.view.tsx
> +    const { comments } = useComments(id);
Хуки нужны для переиспользования логики, как будто хук useComments можно сюда просто заинлайнить

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/Topic/components/Comments/Comments.view.tsx
> +            {comments.map((comment) => (<Comment
```suggestion
            {comments.map(({id, message, created_at}) => (<Comment
```

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/TopicEdit/TopicEdit.helpers.ts
> +    console.log(hasId);
Зачем тут console.log?

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/TopicEdit/TopicEdit.helpers.ts
> +
Это все нужно вынести в useMemo иначе 0 пользы от useCallback внизу, так как ссылка на hasID каждый рендер меняется

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/TopicEdit/TopicEdit.helpers.ts
> +    const onFinishFailed = (errorInfo: Error) => console.log("Failed:", errorInfo);
Пока не очень понятно, зачем тут эта штука(

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/pages/TopicEdit/TopicEdit.view.tsx
> +                            rules={[
Будет удобно вынести все rules в константы в отдельный файл

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/reducers/comments.reducer.ts
> +    user_id: number,
Вообще во фронтенде принято использовать camelCase и данные с бека обычно в него все же перекладывают во время валидации, а не используют as is

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/reducers/topic.reducer.ts
> +    data: {
По идее init state может быть отсутствием каких либо топиков

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/server/controllers/forum/comments.ts
> +        const comments = await getDBComments(id);
try{}catch, тут нужно дополнительно обработать ошибку и в идеале в логи написать что именно пошло не так

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/server/controllers/forum/topics.ts
> +    async get(req: Request, res: Response) {
getAllTopics

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/server/db/forum/actions/comments.ts
> +// TODO: Разобраться с типами
+

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/server/db/init.ts
> +const host = "localhost";
не надо пожалуйста хранить криды в репозитории

2022-03-21 18:39 UTC, DmitryKhitrin commented on src/server/router/apiRoutes.ts
> +apiRouter.delete(`${apiBase}/topics/:id`, ...middlewares, TopicController.delete);
Что бы роутер не превращался в кашу, можно разбить регистрацию роутов на несколько файлов, к примеру на комменты и топики

2022-03-22 18:16 UTC, mikhailbys commented on src/server/router/apiRoutes.ts
> +apiRouter.delete(`${apiBase}/topics/:id`, ...middlewares, TopicController.delete);
👍

2022-03-22 18:16 UTC, mikhailbys commented on src/server/controllers/forum/topics.ts
> +    async get(req: Request, res: Response) {
👍

2022-03-22 18:16 UTC, mikhailbys commented on src/pages/Forum/Forum.helpers.ts
> +} from "react";
👍

2022-03-22 18:16 UTC, mikhailbys commented on src/actions/comments.actions.ts
> +): ThunkAction<void, unknown, unknown, AnyAction> => async (dispatch, _state) => {
👍

2022-03-22 18:16 UTC, mikhailbys commented on src/actions/comments.actions.ts
> +            // loadComment();
Поправил 👍

2022-03-22 19:05 UTC, mikhailbys commented on src/server/db/forum/actions/comments.ts
> +// TODO: Разобраться с типами
👍

2022-03-22 19:06 UTC, mikhailbys commented on src/server/controllers/forum/comments.ts
> +        const comments = await getDBComments(id);
👍

2022-03-22 19:06 UTC, mikhailbys commented on src/actions/comments.actions.ts
> +    payload: { data },
тут исторически во всех экшонах так(

2022-03-24 16:46 UTC, merged