Sprint 1 page maingame
southpark-team/game pull request #4
Opened 2021-12-23 18:41 UTC by mikhailbys

Реализован вызов меню - модального окна с кнопками начать игру, продолжить и выйти из игры - по нажатию Esc. Вызов меню приостанавливает перерендер в методе animate().
 
 Буду рад замечаниям и предложениям)

2021-12-23 21:54 UTC, Roolman commented
В целом все здорово, мне понравилось! Есть небольшие моменты, которые мне кажется поправить стоит.

2021-12-23 21:57 UTC, Roolman requested changes
В целом все здорово, мне понравилось! Есть небольшие моменты, которые мне кажется поправить стоит.

2021-12-23 21:57 UTC, Roolman commented on src/pages/Game/Game.helpers.ts
> +        document.addEventListener('keydown', callMenu);
Я думаю от этого все-таки стоит отписываться при unmount. React об этом предупреждает, если повторно перейти на страницу game.

2021-12-23 21:57 UTC, Roolman commented on src/pages/Game/Game.helpers.ts
> +        world.destroy()
Предлагаю world.destroy() вызывать при unmount компонента, тк может сложиться ситуация, когда пользователь вышел в меню и вместо нажатия кнопочки Перейти на главную в браузерной строке ввел другой роут, таким образом подписки все остаются висеть в воздухе по идее.

2021-12-23 21:57 UTC, Roolman commented on src/components/Modal/Modal.module.scss
> +  // todo через классы стили почему-то не применяются, как у остальных компонент antd
Попробуй все то же самое, но без & . Например,
:global(.ant-modal-body) { 
    background: variables.$background url('../../../assets/images/background.png') no-repeat center center;
}

2021-12-23 21:57 UTC, Roolman commented on src/components/Modal/Modal.module.scss
> +  // todo более того, шрифт тоже не подгружается просто так
Вроде бы все ок - подгрузилось)

2021-12-23 21:57 UTC, Roolman commented on src/components/Modal/Modal.module.scss
> +    width: 400px !important;
Может без !important как-то можно решить? Например, передать в props компонента ширину. Наверняка он принимает это свойство. Вообще предлагаю везде !important убрать, подумать как без него обойтись. Можем пока забить, чтобы 1 спринт сдать, но желательно с этим разобраться)

2021-12-23 21:57 UTC, Roolman commented on src/components/Modal/Modal.module.scss
> +      background: variables.$background url('../../../assets/images/background.png') no-repeat center center !important;
Здесь !important вроде можно убрать просто.

2021-12-23 21:57 UTC, Roolman commented on src/pages/Game/Game.view.tsx
> +   const { active, pause, canvasRef, onStart, onResume, onClose, setUpPauseButton } = useGame();
По идее это удобно - в одном хуке держать логику, но меня немного смущает, что декомпозиция громоздкой получается. Не уверен, что это кошерное решение. Это просто мысли мои)

2021-12-24 09:35 UTC, DmitryKhitrin approved these changes
Не плохо, но взаимодействие в World я бы обсудил

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/components/Modal/Modal.view.tsx
> +    (<CustomModal className={styles.modal} {...props} />);
Не стоит спредить пропсы, лучше описывать и передавать только то, что реально используется. Плюс используя тут напрямую ModalProps, мы завязываемся на интерфейс сторонней библиотеки и на кучу полей, которые на самом деле могут быть и не нужны

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/camera.ts
> +}
EOF

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/eventBus.ts
> +    arrowLeftDown = "arrowLeftDown",
Поля енума именуются с заглавной буквы

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/eventBus.ts
> +}
EOF

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/eventBus.ts
> +    emit(event: string, ...args: unknown[]) {
На самом деле можно заморочиться и написать тип аргументов каждого ивента, тогда использование EventBus станет немного безопаснее)

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/geometry/geometry.ts
> +let _geometryId = 0
Лучше хранить данные в замыкании. В таком виде с ssr, вы начнете использовать единый каунтер id для всех пользователей, а это не очень хорошо

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/geometry/geometry.ts
> +    rectangle = "rectangle",
Поля енума с заглавной буквы

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/geometry/geometry.ts
> +        this.name = ""
Почему имя опциональное?

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/core/object.ts
> +let _object2DId = 0
Про id писал выше

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/game/world/world.ts
> +    init(canvas: HTMLCanvasElement | null) {
Получается очень перегруженный класс, я бы создал по одному иенеджеру на каждый элемент, которые уже внутри себя управляли бы объектами. WallManager, EnemyManager и.т.д.

Класс World просто инитит их

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.helpers.ts
> +        document.addEventListener('keydown', callMenu);
+

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.helpers.ts
> +    const callMenu = (e: KeyboardEvent) => {
Давай обернем в useCallback, что бы не создавать новый инстанс на каждый рендер

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.helpers.ts
> +    const onStart = () => {
useCallback

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.helpers.ts
> +    const onResume = () => {
useCallback

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.helpers.ts
> +    const [pause, setPause] = useState(false);
```suggestion
    const [isPaused, setPause] = useState(false);
```

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.helpers.ts
> +    const [active, setActive] = useState(true);
```suggestion
    const [isActive, setActive] = useState(true);
```

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.helpers.ts
> +}
EOF

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.view.tsx
> +    useEffect(() => {
Полезно написать набор хелперов, к примеру useMountEffect:

```
import {useEffect} from 'react';

/**
 * Вызывает effectCallback при маунте компонента
 */
export const useMountEffect = (effectCallback: () => (() => void) | void) => {
    // тут не должно быть зависимостей
    // eslint-disable-next-line react-hooks/exhaustive-deps
    useEffect(effectCallback, []);
};
```

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Game.view.tsx
> +    useEffect(() => {
Ну или взять отсюда https://github.com/streamich/react-use

2021-12-24 09:35 UTC, DmitryKhitrin commented on src/pages/Game/Menu/Menu.view.tsx
> +    active: boolean;
```suggestion
    isActive: boolean;
```

2021-12-24 10:33 UTC, Roolman commented on src/components/Modal/Modal.view.tsx
> +    (<CustomModal className={styles.modal} {...props} />);
Удалил этот компонент. Оставил просто модал из antd.

2021-12-24 10:36 UTC, Roolman commented on src/game/core/eventBus.ts
> +    emit(event: string, ...args: unknown[]) {
Предлагаю обсудить на созвоне

2021-12-24 10:39 UTC, Roolman commented on src/game/core/geometry/geometry.ts
> +        this.name = ""
Потому что имя само по себе не используется в game engine для обращения к объекту, а может быть использовано на усмотрение разработчика при создании механики самой игры.

2021-12-24 10:39 UTC, Roolman commented on src/game/world/world.ts
> +    init(canvas: HTMLCanvasElement | null) {
Предлагаю обсудить на созвоне

2021-12-24 11:50 UTC, Roolman commented on src/pages/Game/Game.view.tsx
> +    useEffect(() => {
Что кстати думаешь насчет длинной декомпозиции useGame ? Стоит ли разбить на два его или так тоже норм?

2021-12-24 12:07 UTC, Roolman approved these changes

2021-12-27 13:48 UTC, merged