поддержка docker
southpark-team/game pull request #6
Opened 2021-12-23 20:21 UTC by mikhailbys

Добавил dockerfile
На моей машине, как говорится, работает

2021-12-23 22:04 UTC, Roolman requested changes
Вроде ок, но посмотри предложения мои.

2021-12-23 22:04 UTC, Roolman commented on webpack.config.js
> +        port: 3000
Вот это вроде в другом PR было уже, нет? Просто если мерджить начнем, то возможно косяк всплывет.

2021-12-23 22:04 UTC, Roolman commented on Dockerfile
> +FROM node:12
Предлагаю использовать -alpine версию. Для раздачи статики более чем достаточно и лишние зависимости не нужно подкачивать. И собираться гораздо быстрее будет - проверено!)

2021-12-24 14:39 UTC, Roolman approved these changes

2021-12-25 14:46 UTC, etozhealkhipce approved these changes
Все ок

2021-12-25 20:01 UTC, merged