feat: реализовать модалку гамовер
southpark-team/game pull request #9
Opened 2021-12-26 00:06 UTC by etozhealkhipce

2021-12-26 21:52 UTC, Roolman requested changes
Идея интересная, но я думаю нужно что-то другое придумать с логикой завершения игры из-за проблемы, которую в комментарии оставил. 
Как вариант, передавать Enemy общий eventBus, и в момент столкновения генерировать событие GameOver. World слушает это событие и выполняет переданный ему из компонента Game колбэк. В этом колбэке может быть вызов менюшки, вызов world.destroy() и тп.

2021-12-26 21:52 UTC, Roolman commented on src/pages/Game/Game.view.tsx
> +  callGameOverOutside = callGameOver;
Вот это очень хитрый трюк:) Но с ним есть проблема - по нажатию кнопок менюшки мир перерисовывается, и судя по всему заново создается поверх существующего (это я по логам столкновения понял), поэтому мне кажется нужно что-то другое придумать.

2021-12-26 21:52 UTC, Roolman commented on src/pages/Game/Menu/Menu.view.tsx
> +          style={{ color: "white", textAlign: "center", marginBottom: 20 }}
Стили желательно выносить в файл стилей.

2021-12-30 09:38 UTC, mikhailbys approved these changes
<img width="343" alt="Снимок экрана 2021-12-30 в 13 31 09" src="https://user-images.githubusercontent.com/38201290/147739725-4ac097e4-b8bc-428e-aa9a-80ecb77f23ab.png">

Есть нюанс - его либо в трай-кэч оберуть, либо наподумать вынести в отдельную задачку на исправление в будущем

2021-12-30 18:09 UTC, merged